### ISSUE TITLE
[Feature] How would child state transition connect to other parent state through automata scene?

### ISSUE THREAD

**Issue by pushkalkatara** [JdeRobot/VisualStates#18]
Currently, selecting parent state opens a new automata scene where new states can be added.
The parent state must have a transition which automatically redirects it to the child state, and executes the child state. While the automata scene is displaying the child states, the child state must have an option to specify the transition to any state(parent state or child state or any state under root state).
@jmplaza @okanasik Please comment on this.

**Comment by okanasik** [comment]
Dear @pushkalkatara,
In state hierarchy, every subautomata can only have states and transitions between them. That is a design choice to keep hierarchy of subautomatas managable, otherwise it could be quite hard to maintain the whole automata structure. By default, when a parent state is active, subautomata of that state also runs.
