### ISSUE TITLE
None while displaying Global and Local Namespace variables. 

### ISSUE THREAD

**Issue by pushkalkatara** [JdeRobot/VisualStates#60]
This issue might be due to the delay in ipc library. @okanasik please review.

XML File to reproduce the error - 
```
<?xml version="1.0" ?>
<VisualStates>
  <config type="1">
    <buildDependencies/>
    <runDependencies/>
    <topics/>
  </config>
  <global_namespace>
    <functions>def helloWorld(self):
	print(&quot;Hello World&quot;)

</functions>
    <variables>self.variable = 0</variables>
  </global_namespace>
  <libraries/>
  <state id="0" initial="True">
    <posx>0.0</posx>
    <posy>0.0</posy>
    <name>root</name>
    <code></code>
    <timestep>100</timestep>
    <namespace>
      <functions>def helloFromState1(self):
	print(&quot;Hello From State 1&quot;)
	
</functions>
      <variables>self.state1variable = 0</variables>
    </namespace>
    <state id="1" initial="True">
      <posx>959.0</posx>
      <posy>863.0</posy>
      <name>state1</name>
      <code>print(self.namespace.helloFromState1())
print(self.globalNamespace.helloWorld())</code>
      <timestep>100</timestep>
      <namespace>
        <functions></functions>
        <variables></variables>
      </namespace>
    </state>
  </state>
</VisualStates>
```

![namespace-2](https://user-images.githubusercontent.com/21266230/44042840-f9501416-9f3e-11e8-9c58-80488997796c.gif)

**Comment by okanasik** [comment]
I have tested with the latest state from the branch `parsing-namespace`. There is a small error in the order of the parameters, namespace is initialized with 100 (cycleDuration). Can you check this error?

What is the error in this video? I could not get the error. Can you elaborate more?

Okay. I get the error, but this is not an error. You are trying to print the result returned from a method that just prints something. Since you did not return anything deliberately from the method, it just returns `None` and that is why you see `None` in the console.

Also, if you do not run runtime visualizer, there would be anything related to ipc communication.

**Comment by okanasik** [comment]
Fixed.
